version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - laravel

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app
      - db
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6382:6379"
    networks:
      - laravel

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret_password
      MYSQL_ROOT_PASSWORD: super_secret_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
